{
  "patch_root_path": "https://raw.githubusercontent.com/cloudify-cosmo/patchify/master/patch_files/", 
  "patches": [
    {
      "patch_definition_path": "46_local_tasks_restore.json", 
      "patch_description": "Dump/restore support for local tasks.", 
      "patch_files": [
        "46_local_tasks_restore_cloudify_workflows_tasks.py", 
        "46_local_tasks_restore_cloudify_workflows_workflow_context.py"
      ], 
      "patch_hash": "316b313c3bc441abec887e1e0233223c1d0f2021a973a7c5ed2f700dce2ddd42", 
      "patch_id": "46_local_tasks_restore-316b313c3bc441abec887e1e0233223c1d0f2021a973a7c5ed2f700dce2ddd42", 
      "patch_name": "46_local_tasks_restore", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_fix_cfy_status.json", 
      "patch_description": "Allow 'cfy status' command to work even when no Cloudify license is uploaded to the Manager.", 
      "patch_files": [
        "4_6_fix_cfy_status_rest-service_manager_rest_constants.py"
      ], 
      "patch_hash": "07606535edb47639e39dbc9dfe22778127de40eb7d9fbfd075c03e22bc548ea2", 
      "patch_id": "4_6_fix_cfy_status-07606535edb47639e39dbc9dfe22778127de40eb7d9fbfd075c03e22bc548ea2", 
      "patch_name": "4_6_fix_cfy_status", 
      "supports_community": false
    }
  ]
}